// Generated by https://quicktype.io

export interface APIResponse {
  headers:          APIResponseHeaders;
  content:          any;
  version:          string;
  status_code:      number;
  status_text:      string;
  status_texts:     { [key: string]: string };
  data:             any;
  encoding_options: number;
}

export interface APIResponseHeaders {
  headers:                HeadersHeaders;
  cache_control:          any[];
  computed_cache_control: ComputedCacheControl;
  cookies:                any[];
  header_names:           HeaderNames;
}

export interface ComputedCacheControl {
  "no-cache": boolean;
  private:    boolean;
}

export interface HeaderNames {
  "cache-control": string;
  date:            string;
  "content-type":  string;
}

export interface HeadersHeaders {
  "cache-control": string[];
  date:            string[];
  "content-type":  string[];
}
