// Generated by https://quicktype.io

export interface Service {
  id:               number;
  shortDescription: string;
  descriptionEs:    string;
  descriptionEn:    string;
  descriptionFr:    null;
  keywords:         string[];
}
