export interface User {
  id: number;
  username: string;
  username_canonical: string;
  email: string;
  email_canonical: string;
  enabled: boolean;
  salt: string;
  password: string;
  groups: string[];
  roles: Role[];
  social_id: string;
  user_profiles: UserProfile[];
}
// Generated by https://quicktype.io

export interface UserProfile {
  id: number;
  valoration: number;
  phone_number: string;
  comment: string;
  summary: string;
  name: string;
  id_scholarship_fk: IDFk;
  id_user_profile_account_fk: IDUserProfileFk;
  id_user_profile_type_fk: IDUserProfileFk;
  user_profile_briefcases: UserProfileBriefcase[];
}

export interface IDFk {
  id: number;
  short_description: string;
  description_es: string;
  description_en: string;
}

export interface IDUserProfileFk {
  id: number;
  type: string;
}

export interface UserProfileBriefcase {
  id: number;
  comments: string;
  description: string;
  startdate: string;
  enddate: string;
  id_profession_fk: IDFk;
}


// export interface UserProfile {
// id: string;
// valoration: string;
// phone_number: string;
// comment: string;
// summary: string;
// scholarship: Scholarship;
// userProfileType: Role;
// briefcases: Briefcase[];
// }

export interface Scholarship {
  id: number;
  shortDescription: string;
  descriptionEs: string;
  descriptionEn: string;
  descriptionFr: string;
}

export interface Profession {
  id: number;
  shortDescription: string;
  descriptionEs: string;
  descriptionEn: string;
  descriptionFr: string;
}


export interface Role {
  id: number;
  type: string;
}

export interface Briefcase {
  id: number;
  description: string;
  startDate: Date;
  endDate: Date;
  comments: string;
  idProfession: number;
}


